# Generated by Django 4.1.2 on 2022-10-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task',
            new_name='tasks',
        ),
    ]
